var age = 25;
age = true;
console.log(age);
age = 'hello';
console.log(age);
age = { name: 'Sam' };
console.log(age);
var mixed = [];
mixed.push(25, 'Hello', false);
console.log(mixed);
var example;
example = { name: 'Sam', age: 24 };
console.log(example);
example = { name: 'Sam', age: '24' };
console.log(example);
